

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: abathur-project


# 线程池配置
thread-pool:
  config:
    core-pool-size: 4
    max-pool-size: 8
    queue-capacity: 1000
    keep-alive-seconds: 60
