# apisix 基于 docker-compose 本地部署
# 创建docker网络配置 docker network create apisix_network
# 配置中 networks 配置的网桥名称修改为 新创建的网络配置名称
# docker-copmose up -d --build

version: "3"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    container_name: apisix-dashboard
    restart: always
    volumes:
      - ./dashboard_config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - apisix
    ports:
      - "9000:9000"
    networks:
      - apisix_network

  apisix:
    image: apache/apisix:latest
    container_name: apisix
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
    networks:
      - apisix_network

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    restart: always
    volumes:
      - ./etcd_data:/bitnami/etcd/data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix_network

# 网络配置
networks:
  apisix_network:
    external:
      name: apisix_network
